### ISSUE TITLE
これからの予定的なもの

### ISSUE THREAD

**Issue by kotake545** [kotake545/Splatoon#1]
・スナイパーライフルやアイテムを再現する設定の追加　→ チャージャーとサブウェポン。
・スペシャルウェポンの追加。コレはべつのクラス作って動かしたほうがいいかも。
・鉄柵をすり抜けられるようにする
・コマンドの整理
・ちゃんとしたゲームとしてのルールを追加 ガチマッチ と レギュラーマッチがあるらしい。
・スコアボードを使ったゲーム情報の表示 → ScoreBoardUtilのsetSidebarだったかで表示できる
・イカ状態かつ潜っていない時にプレイヤーをイカとして見えるようにする(いらないかな)
・1.8の対応 - 1.8だと羊毛を壊した時のエフェクトが白になったりする。
・操作性の向上 → SNEAKでイカになるようにしてると壁登りづらいからプレイヤーの向いてる方向からW A S D キーを判定して プレイヤーが壁側に移動した時に登る、降りれようにしたい。

**Comment by kotake545** [comment]
当たり判定の変更。
1.8でnet.minecraft.serverからEntityの当たり判定いじれるのかな。

**Comment by Himanoa** [comment]
タスクごとにIssue分けたのでこちらのIssueはクローズしてもいいと思うよ

**Comment by kotake545** [comment]
ということなのでクローズ
